### PR TITLE
Elementwise dtype promotion.

### LINKED ISSUE #143: AssertionError when loading the vertical coordinate of an iris cube.
I am not sure if this is a bug in Biggus or in iris.  If I try to load a cube vertical coordinate directly, like this:

```python
>>> import iris
>>> url = "http://colossus.dl.stevens-tech.edu:8080/thredds/dodsC/latest/Bight_gcmplt.nc"
>>> cube = iris.load_cube(url, 'sea_water_salinity')
>>> cube.coord('sea_surface_height_above_reference_ellipsoid')
<repr(<iris.coords.AuxCoord at 0x7f902daf6750>) failed: AssertionError: >
```

and accessing the points trigger the Exception.

```python
Biggus-0.10.0-py2.7.egg/biggus/__init__.pyc in __init__(self, array1, array2, numpy_op, ma_op)
   2679 
   2680         # TODO: Type-promotion
-> 2681         assert array1.dtype == array2.dtype
   2682         self._array1 = array1
   2683         self._array2 = array2
```

But if I load the `cube.coords()`, then everything works.  [Here](http://nbviewer.ipython.org/urls/gist.githubusercontent.com/ocefpaf/f79b25180950b9d28972/raw/57d04028c5994e8c5c5869c55ed08dcf35300514/coords_bug.ipynb) is a notebook showing this issue.

### PR DESCRIPTION
**Pull request by bjlittle**
Added support for `_Elementwise` dtype promotion.

Closes #143 and #25

### CODE REVIEW

**Comment by bjlittle** [comment]
@rhattersley or @pelson care to take a look? 

Ta :smile:

**Comment by rhattersley** [comment]
:+1:

**Comment by bjlittle** [comment]
@rhattersley Does this PR require further work or consideration before merging?

**Comment by rhattersley** [comment]
Nope. Just time for Travis-CI to do its magic.... which it has now done. :smile:

**Comment by bjlittle** [comment]
Lovely, thanks @rhattersley!

@ocefpaf Game on! :wink:

**Comment by rhattersley** [comment]
> Lovely, thanks @rhattersley!

Not all - thank *you*! You're the one that fixed it! :wink:

**Comment by ocefpaf** [comment]
Thanks @bjlittle!

Just tested #143 and it works like a charm.

http://nbviewer.ipython.org/gist/ocefpaf/3114cb7b55840b94a667

**Comment by bjlittle** [comment]
Awesome! :sunglasses:

**Pull request merged**
