### PR TITLE
Add Array.__orthogonal_indexing__

### PR DESCRIPTION
**Pull request by rhattersley**
See Unidata/netcdf4-python#385 for context.

### CODE REVIEW

**Comment by pelson** [comment]
Really? Does NumpyArrayAdapter not implement non-orthogonal indexing?

**Comment by rhattersley** [comment]
> Does NumpyArrayAdapter not implement non-orthogonal indexing?

I'm a little wary of the double negative, so how about this: *all* biggus arrays provide orthogonal indexing. (The point of the NumpyArrayAdapater is to provide orthogonal indexing even though the underlying array doesn't.)

**Comment by pelson** [comment]
> The point of the NumpyArrayAdapater is to provide orthogonal indexing even though the underlying array doesn't

Ah, OK. Thanks for the clarification.

**Comment by pelson** [comment]
Incidentally, is there a need for OrthoArrayAdapter?

**Comment by rhattersley** [comment]
> is there a need for OrthoArrayAdapter?

It makes the indexing deferred.

**Pull request merged**
