### PR TITLE
ENH: Added elementwise astype for biggus

### LINKED ISSUE #172: Proposed biggus.save enhancement
I propose to add a keyword argument to [save](https://github.com/SciTools/biggus/blob/f150a2074c2f363c5e6c67821c1322e07e089858/biggus/__init__.py) (operation).  The context of this, is to provide the capability to perform dtype conversions on save.  In particular, when saving to NetCDF classic or true CF compliant NetCDF, an unsigned dtype conversion to a signed alternative is necessary.  Having such an operation is not restricted to this example, however, this is my motivation.

```Python
def biggus.save(sources, targets, masked=False, operation=None):
    """
    Save the numeric results of each source into its corresponding target.

    Parameters
    ---------------
    ...
    operation : callable
        Callable to apply to the source before saving.
    ...

```

Happy to make the enhancement myself if this is deemed useful.

### PR DESCRIPTION
**Pull request by cpelley**
Closes #172

### CODE REVIEW

**Comment by pelson** [comment]
There is already an astype in biggus: https://github.com/SciTools/biggus/blob/3a6ef14ae57dac7555ffffeb05eaee6ffa219a29/biggus/__init__.py#L531

**Comment by cpelley** [comment]
I saw this, but correct me if I'm wrong, that will make the array concrete before doing the dtype change?

**Comment by pelson** [comment]
> but correct me if I'm wrong, that will make the array concrete before doing the dtype change?

I hope you're wrong, otherwise there is no advantage over ```np.asarray(biggus_array).astype(np.float32)```...

**Comment by pelson** [comment]
Either way, the AsTypeArray was added after Elementwise was extended to single arguments. There is plenty of room for rationalisation and simplification on that front! :+1:

**Comment by cpelley** [comment]
Thanks @pelson, I'll do some experimentation

**Comment by cpelley** [comment]
I think your right!  I'll close for now, thanks @pelson

**Comment by rhattersley** [comment]
@cpelley - I'm sorry for pointing you in the wrong direction and wasting your time! :unamused:

**Comment by cpelley** [comment]
No problem at all.  Thank you both for your interest in this

**Pull request closed without merging**
