### PR TITLE
Added BroadcastArray for broadcasting dimensions of length 1.

### PR DESCRIPTION
**Pull request by pelson**
The alternative fix for #127. :wink:

### CODE REVIEW

**Comment by rhattersley** [comment]
That was quick typing! :grin:

**Comment by rhattersley** [comment]
@pelson - are you planning on adding any more commits I should I merge?

**Comment by pelson** [comment]
I have nothing lined up for this branch.

**Comment by rhattersley** [comment]
> I have nothing lined up for this branch.

OK - thanks.

**Pull request merged**
