### PR TITLE
Extend deepcopy patch to cover numpy slice bug

### PR DESCRIPTION
**Pull request by bjlittle**
This PR extends the temporary patch introduced by #159 to cover another related NumPy bug, which is encountered when performing a deepcopy of a sliced array (that has incorrect `strides` assigned to it by NumPy)

### CODE REVIEW

**Comment by pelson** [comment]
You are seeing some interesting travis issues. Is this #151 related?

**Comment by pelson** [comment]
Ping. We should get this merged and released.

**Comment by marqh** [comment]
> Ping. We should get this merged and released.

indeed we should.  What are the test failures related to, does anyone know?

Is this intrinsic to this PR or something we can work around?

**Comment by pelson** [comment]
At a guess, I'd say the version of numpy had changed, and it wasn't supported with biggus yet (as per #151). We could try pinning that in the requirements.txt.

**Pull request merged**
